"""Add der_category and der_merchant to transactions

Revision ID: c61541b90ee5
Revises: 4f9d76693b6d
Create Date: 2026-01-02 11:00:11.021331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c61541b90ee5'
down_revision: Union[str, Sequence[str], None] = '4f9d76693b6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('der_category', sa.String(length=100), nullable=True))
    op.add_column('transactions', sa.Column('der_merchant', sa.String(length=255), nullable=True))
    op.create_index('ix_transactions_account_der_category', 'transactions', ['account_id', 'der_category'], unique=False)
    op.create_index(op.f('ix_transactions_der_category'), 'transactions', ['der_category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_der_category'), table_name='transactions')
    op.drop_index('ix_transactions_account_der_category', table_name='transactions')
    op.drop_column('transactions', 'der_merchant')
    op.drop_column('transactions', 'der_category')
    # ### end Alembic commands ###
